# Generated by Django 5.0.7 on 2024-07-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media/files', verbose_name='File'),
        ),
    ]
