# Generated by Django 5.0.7 on 2024-07-31 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_media_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='customerfeedback',
            options={'verbose_name': 'Customer Feedback', 'verbose_name_plural': 'Customer Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Medias'},
        ),
        migrations.AlterModelOptions(
            name='ourinstagramstory',
            options={'verbose_name': 'Instagram Story', 'verbose_name_plural': 'Instagram Stories'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'gif', 'mp4', 'mp3', 'wav', 'avi', 'doc', 'pdf'])], verbose_name='File'),
        ),
    ]
