# Generated by Django 5.0.7 on 2024-07-31 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_ourinstagramstory_story_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourinstagramstory',
            name='story_link',
            field=models.URLField(validators=[django.core.validators.URLValidator(regex=django.core.validators.RegexValidator(regex='http(s?)://)?(?:www.)?(?:instagram|instagr).([a-z])+/(\\w*)?/?'))], verbose_name='Story Link'),
        ),
    ]
