# Generated by Django 5.0.7 on 2024-07-31 13:14

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_ourinstagramstory_story_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourinstagramstory',
            name='story_link',
            field=models.URLField(validators=[common.utils.instagram_story_validator], verbose_name='Story Link'),
        ),
    ]
