# Generated by Django 5.0.7 on 2024-07-31 12:17

import accounts.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress_verificationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('\\+998([0-9]{2})([0-9]{3})(\\d{2})(\\d{2})')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('\\+998([0-9]{2})([0-9]{3})(\\d{2})(\\d{2})')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pin_code',
            field=models.CharField(max_length=60, verbose_name='Pin Code'),
        ),
        migrations.AlterField(
            model_name='verificationotp',
            name='code',
            field=models.IntegerField(validators=[accounts.utils.check_otp_code], verbose_name='Otp code'),
        ),
    ]
