# Generated by Django 5.0.7 on 2024-08-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationotp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
