# Generated by Django 5.0.7 on 2024-08-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_verificationotp_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerificationOtp',
            new_name='VerifictionOtp',
        ),
    ]
