# Generated by Django 5.0.7 on 2024-07-31 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_useraddress_verificationotp'),
        ('common', '0002_alter_media_file'),
        ('products', '0003_category_level_category_lft_category_rght_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, verbose_name='code')),
                ('max_limit_price', models.FloatField(verbose_name='max limit price')),
                ('percentage', models.FloatField(verbose_name='Percentage')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('max_limit', models.IntegerField(verbose_name='max limits')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('zip_code', models.CharField(max_length=10, verbose_name='zip_code')),
                ('street', models.CharField(max_length=120, verbose_name='street')),
                ('address', models.TextField(verbose_name='address')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='common.region')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='Card number')),
                ('card_name', models.CharField(max_length=120, verbose_name='card name')),
                ('expiry_date', models.DateField(verbose_name='Expiration date')),
                ('cvv', models.CharField(max_length=3, verbose_name='CVV')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('subtotal', models.FloatField(verbose_name='subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='price')),
                ('high', models.FloatField(verbose_name='high')),
                ('width', models.FloatField(verbose_name='width')),
                ('weight', models.FloatField(verbose_name='weight')),
                ('delivery_time', models.TimeField(verbose_name='delivery time')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tariffs', to='orders.branch')),
                ('regions', models.ManyToManyField(related_name='delivery_tariffs', to='common.region')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='created', max_length=60, verbose_name='Status')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('payment_status', models.CharField(blank=True, choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=60, null=True, verbose_name='Payment Status')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.useraddress')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.discount')),
                ('items', models.ManyToManyField(related_name='orders', to='orders.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
